version: '3.8'

services:
  python_calculator:
    build:
      context: ./numberTwo
      dockerfile: Dockerfile
    image: python_calculator_image
    container_name: python_calculator_container
    tty: true
    stdin_open: true

  c_calculator:
    build:
      context: ./numberThree
      dockerfile: Dockerfile
    image: c_calculator_image
    container_name: c_calculator_container
    tty: true
    stdin_open: true

